# Constants for game configuration
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "GetOut"
PLAYER_GRAVITY = 1
PLAYER_JUMP_SPEED = 15
PLAYER_START_X = 100
PLAYER_START_Y = 150
GROUND_HEIGHT = 100
OBSTACLE_SPAWN_RATE = 1.5  # Seconds between spawns
