# Constants for game configuration
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
SCREEN_TITLE = "GetOut"
PLAYER_GRAVITY = 1
PLAYER_JUMP_SPEED = 15
PLAYER_START_X = 100
PLAYER_START_Y = 150
GROUND_HEIGHT = 100
OBSTACLE_SPAWN_RATE = 1.5  # Seconds between spawns
BUG_MIN_COUNT = 5
BUG_MAX_COUNT = 7
BUG_SCALE = 0.3
BUG_SPEED = -2
GAME_RED = (218, 94, 83)  # Equivalent to '#da5e53' in RGB
